# Generated by Django 4.0.6 on 2022-07-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ended',
            field=models.BooleanField(default=True),
        ),
    ]
