# Generated by Django 4.0.6 on 2022-07-23 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0003_alter_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 23, 8, 50, 21, 31942)),
        ),
    ]
