# Generated by Django 4.0.6 on 2022-07-26 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0007_alter_session_date_alter_move_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 26, 6, 4, 22, 442182)),
        ),
        migrations.AlterModelTable(
            name='session',
            table='sessionstable',
        ),
        migrations.AlterModelTable(
            name='set',
            table='setstable',
        ),
    ]
